/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salonhabana.layouts;

import java.awt.CardLayout;
import java.awt.GridBagConstraints;
import javax.swing.JPanel;

/**
 *
 * @author sersu
 */
public class ElementsReservaGrid extends javax.swing.JPanel {

    private static final String btgItems[] = new String[] {"Banquete", "Jornada", "Congreso"};
    
    /**
     * Creates new form ElementsReservaGrid
     */
    public ElementsReservaGrid() {
        initComponents();
        this.customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btgTipoEvento = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        spiFechaEvento = new javax.swing.JSpinner();
        lblTipEvento = new javax.swing.JLabel();
        rbtBanquete = new javax.swing.JRadioButton();
        rbtJornada = new javax.swing.JRadioButton();
        rbtCongreso = new javax.swing.JRadioButton();
        lblNumPersonas = new javax.swing.JLabel();
        spiNumPerso = new javax.swing.JSpinner();
        lblTipCocina = new javax.swing.JLabel();
        cmbTipCocina = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txfTelefono = new javax.swing.JTextField();

        btgTipoEvento.add(this.rbtBanquete);
        btgTipoEvento.add(this.rbtJornada);
        btgTipoEvento.add(this.rbtCongreso);

        setLayout(new java.awt.GridBagLayout());

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(lblNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(txfNombre, gridBagConstraints);

        lblTelefono.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        add(lblTelefono, gridBagConstraints);

        lblDireccion.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(lblDireccion, gridBagConstraints);

        txfDireccion.setToolTipText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txfDireccion, gridBagConstraints);

        lblFecha.setText("Fecha Evento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        add(lblFecha, gridBagConstraints);

        spiFechaEvento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(spiFechaEvento, gridBagConstraints);

        lblTipEvento.setText("Tipo Evento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        add(lblTipEvento, gridBagConstraints);

        rbtBanquete.setText("Banquete");
        rbtBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBanquetehlrRbtBanquete(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        add(rbtBanquete, gridBagConstraints);

        rbtJornada.setText("Jornada");
        rbtJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtJornadahlrRbtJornada(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        add(rbtJornada, gridBagConstraints);

        rbtCongreso.setText("Congreso");
        rbtCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCongresohlrRbtCongreso(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        add(rbtCongreso, gridBagConstraints);

        lblNumPersonas.setText("NºPersonas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        add(lblNumPersonas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        add(spiNumPerso, gridBagConstraints);

        lblTipCocina.setText("Tipo de Cocina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        add(lblTipCocina, gridBagConstraints);

        cmbTipCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        add(cmbTipCocina, gridBagConstraints);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarhalrOnClickAceptar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        add(btnAceptar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarhalrOnClickCancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        add(btnCancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        add(txfTelefono, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void customInit() {
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        this.card = new CardLayout();
        this.panTipEvento = new JPanel(this.card);
        JPanel emptyPanel = new JPanel();
        emptyPanel.setOpaque(false);
        
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.weightx = 3;
        
        this.panTipEvento.add(emptyPanel, ElementsReservaGrid.btgItems[0]);
        this.panTipEvento.add(emptyPanel, ElementsReservaGrid.btgItems[1]);
        this.panTipEvento.add(new PanTipoEvento(), ElementsReservaGrid.btgItems[2]);
        
        //getContentPane().add(this.panTipEvento, gridBagConstraints);
    }
    
    private void rbtBanquetehlrRbtBanquete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBanquetehlrRbtBanquete
        this.card.show(this.panTipEvento, ElementsReservaGrid.btgItems[0]);
    }//GEN-LAST:event_rbtBanquetehlrRbtBanquete

    private void rbtJornadahlrRbtJornada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtJornadahlrRbtJornada
        this.card.show(this.panTipEvento, ElementsReservaGrid.btgItems[1]);
    }//GEN-LAST:event_rbtJornadahlrRbtJornada

    private void rbtCongresohlrRbtCongreso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCongresohlrRbtCongreso
        this.card.show(this.panTipEvento, ElementsReservaGrid.btgItems[2]);
    }//GEN-LAST:event_rbtCongresohlrRbtCongreso

    private void btnAceptarhalrOnClickAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarhalrOnClickAceptar
        // TODO: Go to main title
    }//GEN-LAST:event_btnAceptarhalrOnClickAceptar

    private void btnCancelarhalrOnClickCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarhalrOnClickCancelar
        //this.dispose();
    }//GEN-LAST:event_btnCancelarhalrOnClickCancelar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipoEvento;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbTipCocina;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPersonas;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipCocina;
    private javax.swing.JLabel lblTipEvento;
    private javax.swing.JRadioButton rbtBanquete;
    private javax.swing.JRadioButton rbtCongreso;
    private javax.swing.JRadioButton rbtJornada;
    private javax.swing.JSpinner spiFechaEvento;
    private javax.swing.JSpinner spiNumPerso;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
    private CardLayout card;
    private JPanel panTipEvento;
}
