/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salonhabana.layouts;

/**
 *
 * @author sersu
 */
public class PanTipoEvento extends javax.swing.JPanel {

    /**
     * Creates new form PanTipoEvento
     */
    public PanTipoEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNumJor = new javax.swing.JPanel();
        lblNumJorn = new javax.swing.JLabel();
        spiNumJorn = new javax.swing.JSpinner();
        panReqHabit = new javax.swing.JPanel();
        chbReqHabitacio = new javax.swing.JCheckBox();
        panTipHabit = new javax.swing.JPanel();
        lblTipHabitacion = new javax.swing.JLabel();
        cmbTipHabitacion = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panNumJor.setOpaque(false);

        lblNumJorn.setText("NºJornadas:");
        lblNumJorn.setAlignmentX(0.5F);
        lblNumJorn.setAlignmentY(0.0F);
        panNumJor.add(lblNumJorn);
        panNumJor.add(spiNumJorn);

        add(panNumJor);

        panReqHabit.setOpaque(false);

        chbReqHabitacio.setText("¿Requiere de habitación?");
        chbReqHabitacio.setAlignmentX(0.5F);
        chbReqHabitacio.setAlignmentY(1.0F);
        chbReqHabitacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlrChbReqHabitacio(evt);
            }
        });
        panReqHabit.add(chbReqHabitacio);

        add(panReqHabit);

        panTipHabit.setOpaque(false);

        lblTipHabitacion.setText("Tipo Habitación:");
        panTipHabit.add(lblTipHabitacion);

        cmbTipHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipHabitacion.setEnabled(false);
        panTipHabit.add(cmbTipHabitacion);

        add(panTipHabit);
    }// </editor-fold>//GEN-END:initComponents

    private void hlrChbReqHabitacio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlrChbReqHabitacio
        this.cmbTipHabitacion.setEnabled(this.chbReqHabitacio.isSelected());
    }//GEN-LAST:event_hlrChbReqHabitacio


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbReqHabitacio;
    private javax.swing.JComboBox<String> cmbTipHabitacion;
    private javax.swing.JLabel lblNumJorn;
    private javax.swing.JLabel lblTipHabitacion;
    private javax.swing.JPanel panNumJor;
    private javax.swing.JPanel panReqHabit;
    private javax.swing.JPanel panTipHabit;
    private javax.swing.JSpinner spiNumJorn;
    // End of variables declaration//GEN-END:variables
}
