/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salonhabana.layouts;

/**
 *
 * @author sersu
 */
public class PanTipoEvento extends javax.swing.JPanel {

    /**
     * Creates new form PanTipoEvento
     */
    public PanTipoEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumJorn = new javax.swing.JLabel();
        spiNumJorn = new javax.swing.JSpinner();
        chbReqHabitacio = new javax.swing.JCheckBox();
        lblTipHabitacion = new javax.swing.JLabel();
        cmbTipHabitacion = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 0, 51));

        lblNumJorn.setText("NºJornadas:");
        add(lblNumJorn);
        add(spiNumJorn);

        chbReqHabitacio.setText("¿Requiere de habitación?");
        chbReqHabitacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlrChbReqHabitacio(evt);
            }
        });
        add(chbReqHabitacio);

        lblTipHabitacion.setText("Tipo Habitación:");
        add(lblTipHabitacion);

        cmbTipHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipHabitacion.setEnabled(false);
        add(cmbTipHabitacion);
    }// </editor-fold>//GEN-END:initComponents

    private void hlrChbReqHabitacio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlrChbReqHabitacio
        this.cmbTipHabitacion.setEnabled(this.chbReqHabitacio.isSelected());
    }//GEN-LAST:event_hlrChbReqHabitacio


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbReqHabitacio;
    private javax.swing.JComboBox<String> cmbTipHabitacion;
    private javax.swing.JLabel lblNumJorn;
    private javax.swing.JLabel lblTipHabitacion;
    private javax.swing.JSpinner spiNumJorn;
    // End of variables declaration//GEN-END:variables
}
