/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.salonhabana.layouts;

/**
 *
 * @author sersu
 */
public class Prueba2 extends javax.swing.JDialog {

    /**
     * Creates new form Prueba2
     */
    public Prueba2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txfTelefono = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        spiFechaEvento = new javax.swing.JSpinner();
        spiNumPerso = new javax.swing.JSpinner();
        cmbTipCocina = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNumPerso = new javax.swing.JLabel();
        lblTipCocina = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtCongreso = new javax.swing.JRadioButton();
        rbtBanquete = new javax.swing.JRadioButton();
        lblTipEvento = new javax.swing.JLabel();
        rbtJornada = new javax.swing.JRadioButton();
        panOpEvento = new javax.swing.JPanel();
        lblNumJorn = new javax.swing.JLabel();
        spiNumJorn = new javax.swing.JSpinner();
        chbReqHabitacio = new javax.swing.JCheckBox();
        lblTipHabitacion = new javax.swing.JLabel();
        cmbTipHabitacion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, -1));

        txfNombre.setToolTipText("Escriba su nombre");
        jPanel2.add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        txfTelefono.setToolTipText("Escriba su teléfono");
        jPanel2.add(txfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 90, -1));

        lblDireccion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblDireccion.setText("Dirección:");
        jPanel2.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 70, -1));

        txfDireccion.setToolTipText("Indique su calle con número, puerta, pis, etc");
        jPanel2.add(txfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 310, -1));

        lblFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblFecha.setText("Fecha Evento:");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        spiFechaEvento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        spiFechaEvento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        spiFechaEvento.setToolTipText("Establezca cuándo se realizará el evento");
        jPanel2.add(spiFechaEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        spiNumPerso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        spiNumPerso.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)1), Short.valueOf((short)1), Short.valueOf((short)50), Short.valueOf((short)1)));
        spiNumPerso.setToolTipText("Escriba cuántas personas assistirán al evento");
        jPanel2.add(spiNumPerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        cmbTipCocina.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbTipCocina.setModel(new javax.swing.DefaultComboBoxModel<>(this.TIPO_COCINA.clone()));
        cmbTipCocina.setToolTipText("Indique qué tipo de cocina se empleará");
        jPanel2.add(cmbTipCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 90, -1));

        btnAceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarhalrOnClickAceptar(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarhalrOnClickCancelar(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        lblNumPerso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNumPerso.setText("NºPersonas:");
        jPanel2.add(lblNumPerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblTipCocina.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTipCocina.setText("Tipo de Cocina:");
        jPanel2.add(lblTipCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        rbtCongreso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbtCongreso.setText("Congreso");
        rbtCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCongresohlrRbtCongreso(evt);
            }
        });

        rbtBanquete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbtBanquete.setText("Banquete");
        rbtBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBanquetehlrRbtBanquete(evt);
            }
        });

        lblTipEvento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTipEvento.setText("Tipo evento:");

        rbtJornada.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        rbtJornada.setText("Jornada");
        rbtJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtJornadahlrRbtJornada(evt);
            }
        });

        panOpEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panOpEvento.setVisible(false);

        lblNumJorn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNumJorn.setText("NºJornadas:");
        panOpEvento.add(lblNumJorn);

        spiNumJorn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        spiNumJorn.setToolTipText("La duración del evento en jornadas");
        spiNumJorn.setPreferredSize(new java.awt.Dimension(64, 29));
        panOpEvento.add(spiNumJorn);

        chbReqHabitacio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        chbReqHabitacio.setText("¿Requiere de habitación?");
        chbReqHabitacio.setToolTipText("Deséa incluir habitaciones");
        chbReqHabitacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbReqHabitaciohlrChbReqHabitacio(evt);
            }
        });
        panOpEvento.add(chbReqHabitacio);

        lblTipHabitacion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTipHabitacion.setText("Tipo Habitación:");
        panOpEvento.add(lblTipHabitacion);

        cmbTipHabitacion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbTipHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(Reserva.TIPO_HABITACION));
        cmbTipHabitacion.setToolTipText("Escoja cómo será la habitación");
        cmbTipHabitacion.setEnabled(false);
        panOpEvento.add(cmbTipHabitacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panOpEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipEvento)
                        .addGap(18, 18, 18)
                        .addComponent(rbtBanquete)
                        .addGap(18, 18, 18)
                        .addComponent(rbtJornada)
                        .addGap(18, 18, 18)
                        .addComponent(rbtCongreso)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipEvento)
                    .addComponent(rbtBanquete)
                    .addComponent(rbtJornada)
                    .addComponent(rbtCongreso))
                .addGap(18, 18, 18)
                .addComponent(panOpEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 400, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarhalrOnClickAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarhalrOnClickAceptar
        // TODO: Go to main title
    }//GEN-LAST:event_btnAceptarhalrOnClickAceptar

    private void btnCancelarhalrOnClickCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarhalrOnClickCancelar
        this.dispose();
    }//GEN-LAST:event_btnCancelarhalrOnClickCancelar

    private void rbtCongresohlrRbtCongreso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCongresohlrRbtCongreso
        this.setSize(this.getSize().width + 20, this.getSize().height + 110);
        this.panOpEvento.setVisible(true);
        this.spiNumPerso.setModel(new SpinnerNumberModel(Short.valueOf((short)1), Short.valueOf((short)1), Short.valueOf((short)50), Short.valueOf((short)1)));
    }//GEN-LAST:event_rbtCongresohlrRbtCongreso

    private void rbtBanquetehlrRbtBanquete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBanquetehlrRbtBanquete
        this.panOpEvento.setVisible(false);
        //this.setSize(465, 370);
        this.setSize(this.frameWidth, this.frameHeigh);
        this.spiNumPerso.setModel(new SpinnerNumberModel(Short.valueOf((short)1), Short.valueOf((short)1), Short.valueOf((short)100), Short.valueOf((short)1)));
    }//GEN-LAST:event_rbtBanquetehlrRbtBanquete

    private void rbtJornadahlrRbtJornada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtJornadahlrRbtJornada
        this.panOpEvento.setVisible(false);
        //this.setSize(465, 370);
        this.setSize(this.frameWidth, this.frameHeigh);
        this.spiNumPerso.setModel(new SpinnerNumberModel(Short.valueOf((short)1), Short.valueOf((short)1), Short.valueOf((short)50), Short.valueOf((short)1)));
    }//GEN-LAST:event_rbtJornadahlrRbtJornada

    private void chbReqHabitaciohlrChbReqHabitacio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbReqHabitaciohlrChbReqHabitacio
        this.cmbTipHabitacion.setEnabled(this.chbReqHabitacio.isSelected());
    }//GEN-LAST:event_chbReqHabitaciohlrChbReqHabitacio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prueba2 dialog = new Prueba2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chbReqHabitacio;
    private javax.swing.JComboBox<String> cmbTipCocina;
    private javax.swing.JComboBox<String> cmbTipHabitacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumJorn;
    private javax.swing.JLabel lblNumPerso;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipCocina;
    private javax.swing.JLabel lblTipEvento;
    private javax.swing.JLabel lblTipHabitacion;
    private javax.swing.JPanel panOpEvento;
    private javax.swing.JRadioButton rbtBanquete;
    private javax.swing.JRadioButton rbtCongreso;
    private javax.swing.JRadioButton rbtJornada;
    private javax.swing.JSpinner spiFechaEvento;
    private javax.swing.JSpinner spiNumJorn;
    private javax.swing.JSpinner spiNumPerso;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
}
