/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.salonhabana.layouts;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author sersu
 */
public class ReservaGridBag extends javax.swing.JDialog {

    private static final String btgItems[] = new String[] {"Banquete", "Jornada", "Congreso"};
    
    /**
     * Creates new form ReservaGridBag
     */
    public ReservaGridBag(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton14 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        btgTipoEvento = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        spiFechaEvento = new javax.swing.JSpinner();
        lblTipEvento = new javax.swing.JLabel();
        rbtBanquete = new javax.swing.JRadioButton();
        rbtJornada = new javax.swing.JRadioButton();
        rbtCongreso = new javax.swing.JRadioButton();
        lblNumPersonas = new javax.swing.JLabel();
        spiNumPerso = new javax.swing.JSpinner();
        lblTipCocina = new javax.swing.JLabel();
        cmbTipCocina = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txfTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        jButton14.setText("jButton14");

        jButton38.setText("jButton38");

        jButton54.setText("jButton54");

        btgTipoEvento.add(this.rbtBanquete);
        btgTipoEvento.add(this.rbtJornada);
        btgTipoEvento.add(this.rbtCongreso);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reserva");
        setMinimumSize(new java.awt.Dimension(364, 459));
        setPreferredSize(new java.awt.Dimension(364, 459));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(lblNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txfNombre, gridBagConstraints);

        lblTelefono.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(lblTelefono, gridBagConstraints);

        lblDireccion.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(lblDireccion, gridBagConstraints);

        txfDireccion.setToolTipText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txfDireccion, gridBagConstraints);

        lblFecha.setText("Fecha Evento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        getContentPane().add(lblFecha, gridBagConstraints);

        spiFechaEvento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(spiFechaEvento, gridBagConstraints);

        lblTipEvento.setText("Tipo Evento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        getContentPane().add(lblTipEvento, gridBagConstraints);

        rbtBanquete.setText("Banquete");
        rbtBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlrRbtBanquete(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        getContentPane().add(rbtBanquete, gridBagConstraints);

        rbtJornada.setText("Jornada");
        rbtJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlrRbtJornada(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        getContentPane().add(rbtJornada, gridBagConstraints);

        rbtCongreso.setText("Congreso");
        rbtCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlrRbtCongreso(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        getContentPane().add(rbtCongreso, gridBagConstraints);

        lblNumPersonas.setText("NºPersonas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(lblNumPersonas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(spiNumPerso, gridBagConstraints);

        lblTipCocina.setText("Tipo de Cocina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(lblTipCocina, gridBagConstraints);

        cmbTipCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(cmbTipCocina, gridBagConstraints);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halrOnClickAceptar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(btnAceptar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halrOnClickCancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(btnCancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txfTelefono, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));
        jPanel5.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));
        jPanel6.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel6, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));
        jPanel7.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(0, 0, 204));
        jPanel8.setMinimumSize(new java.awt.Dimension(22, 22));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(22, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInit() {
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        this.card = new CardLayout();
        this.panTipEvento = new JPanel(this.card);
        JPanel emptyPanel = new JPanel();
        emptyPanel.setOpaque(false);
        
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        
        this.panTipEvento.add(emptyPanel, ReservaGridBag.btgItems[0]);
        this.panTipEvento.add(emptyPanel, ReservaGridBag.btgItems[1]);
        this.panTipEvento.add(new PanTipoEvento(), ReservaGridBag.btgItems[2]);
        
        getContentPane().add(this.panTipEvento, gridBagConstraints);
    }
    
    private void halrOnClickAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halrOnClickAceptar
        // TODO: Go to main title
    }//GEN-LAST:event_halrOnClickAceptar

    private void halrOnClickCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halrOnClickCancelar
        this.dispose();
    }//GEN-LAST:event_halrOnClickCancelar

    private void hlrRbtBanquete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlrRbtBanquete
        this.card.show(this.panTipEvento, ReservaGridBag.btgItems[0]);
    }//GEN-LAST:event_hlrRbtBanquete

    private void hlrRbtJornada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlrRbtJornada
        this.card.show(this.panTipEvento, ReservaGridBag.btgItems[1]);
    }//GEN-LAST:event_hlrRbtJornada

    private void hlrRbtCongreso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlrRbtCongreso
        this.card.show(this.panTipEvento, ReservaGridBag.btgItems[2]);
    }//GEN-LAST:event_hlrRbtCongreso

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReservaGridBag dialog = new ReservaGridBag(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipoEvento;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbTipCocina;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPersonas;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipCocina;
    private javax.swing.JLabel lblTipEvento;
    private javax.swing.JRadioButton rbtBanquete;
    private javax.swing.JRadioButton rbtCongreso;
    private javax.swing.JRadioButton rbtJornada;
    private javax.swing.JSpinner spiFechaEvento;
    private javax.swing.JSpinner spiNumPerso;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
    private CardLayout card;
    private JPanel panTipEvento;
}
